import '@supermapgis/mapboxgl/theme-chalk/base.scss'
import '@supermapgis/mapboxgl/theme-chalk/query.scss'
import '@supermapgis/mapboxgl/theme-chalk/base-attribute-popup.scss'
import 'swiper/swiper-bundle.css'
import 'quill/dist/quill.snow.css'
