export {default as WebMap} from './WebMap.vue'
export {default as LayerList} from './LayerList.vue'
export {default as Pan} from './Pan.vue'
export {default as Zoom} from './Zoom.vue'
export {default as Scale} from './Scale.vue'
export {default as Chart} from './Chart.vue'
export {default as Map} from './Map.vue'
export {default as MiniMap} from './MiniMap.vue'
// export {default as Measure} from './Measure.vue'
export {default as Search} from './Search.vue'
export {default as Legend} from './Legend.vue'
export {default as Query} from './Query.vue'

