<script setup lang="ts">
import type { SceneLayerConfigNode } from '../types'
import WebScene from '@supermapgis/mapboxgl/components/web-scene/webscene.vue'
import SceneLayerManager from '../scene-layer-manager.vue'
import '../style'

defineOptions({
  name: 'SceneLayerManagerDemo'
})
const defaultProps = {
  sceneUrl: '/iportal/web/scenes/1773481018',
  widgetsPath: '/iportal/apps/earth/v2/SuperMap3D/Widgets/widgets.css',
  cesiumPath: '/iportal/apps/earth/v2/SuperMap3D/SuperMap3D.js',
  openConfigPath: '/iportal/apps/earth/v2/lib/OpenConfig.js',
  options: {
    scanEffect: {
      status: true,
      type: 'noScan',
      centerPostion: {
        x: null,
        y: null,
        z: null
      },
      period: 2000,
      speed: 500
    },
    position: {
      orientation: {
        pitch: null,
        roll: null,
        heading: null
      },
      destination: {
        x: null,
        y: null,
        z: null
      }
    }
  }
}
const layerConfig: SceneLayerConfigNode[] = [
  {
    children: [
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 'map',
        subdomains: '',
        defaultLoad: true,
        name: '天地图标记层',
        id: 'b8b25c51-bae1-4d9b-9ced-67df36fcd2a4',
        fields: [],
        config: {
          highlightColor: '#0afbf7',
          zoomOffset: 1,
          maximumLevel: 18,
          transparentBackColor: '#000000',
          transparentBackColorTolerance: 0,
          attrGeometryType: '',
          type: 'url',
          url: 'https://t5.tianditu.gov.cn/cia_c/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=cia&STYLE=default&TILEMATRIXSET=c&FORMAT=tiles&TILECOL={x}&TILEROW={y}&TILEMATRIX={z}&tk=436ce7e50d27eede2f2929307e6b33c0',
          minimumLevel: 0,
          zIndex: 3
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 'map',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '天地图地形',
        id: '18fe7255-2401-4c05-d757-d789ea4c481a',
        fields: [],
        config: {
          highlightColor: '#0afbf7',
          zoomOffset: 1,
          maximumLevel: 18,
          transparentBackColor: '#000000',
          transparentBackColorTolerance: 0,
          attrGeometryType: '',
          type: 'url',
          url: 'https://t2.tianditu.gov.cn/vec_c/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=vec&STYLE=default&TILEMATRIXSET=c&FORMAT=tiles&TILECOL={x}&TILEROW={y}&TILEMATRIX={z}&tk=436ce7e50d27eede2f2929307e6b33c0',
          minimumLevel: 0,
          zIndex: 2
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 'map',
        autoLocate: false,
        subdomains: '',
        defaultLoad: true,
        name: '天地图影像',
        id: 'cb4d7545-0dcd-494d-ed69-bf252d86d6dc',
        fields: [],
        config: {
          highlightColor: '#0afbf7',
          zoomOffset: 1,
          maximumLevel: 18,
          transparentBackColor: '#000000',
          transparentBackColorTolerance: 0,
          attrGeometryType: '',
          type: 'url',
          url: 'https://t0.tianditu.gov.cn/img_c/wmts?service=WMTS&version=1.0.0&request=GetTile&tilematrix={z}&layer=img&style=default&tilerow={y}&tilecol={x}&tilematrixset=c&format=tiles&tk=436ce7e50d27eede2f2929307e6b33c0',
          minimumLevel: 0,
          zIndex: 1
        },
        propertyId: '',
        key: ''
      }
    ],
    name: '底图',
    id: '0268bbb7-6db7-401b-ef2d-67051b0f0a40',
    checkEnabled: false,
    config: {}
  },
  {
    children: [
      {
        resourceId: '',
        legendIcon: '/zgis-map/public/legend-icon/ic_cl.svg',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 'data',
        autoLocate: false,
        subdomains: '',
        defaultLoad: true,
        name: '传统村落保护点位',
        showPopup: true,
        id: '7f123d61-012d-4d5b-d917-103a4844f46a',
        fields: [
          {
            prop: 'title',
            show: true,
            label: '名称'
          },
          {
            prop: 'cq_ctclpoint_protect',
            show: true,
            label: '保护级别'
          },
          {
            prop: 'cq_wgb_time',
            show: true,
            label: '批次'
          },
          {
            prop: 'cq_wgb_city',
            show: true,
            label: '所在市'
          },
          {
            prop: 'cq_wgb_county',
            show: true,
            label: '所在区县'
          },
          {
            prop: 'cq_ctclpoint_address',
            show: true,
            label: '地址'
          }
        ],
        config: {
          heightField: '',
          idField: '',
          cluster: 0,
          requestMethod: 'GET',
          icon: {
            width: 16,
            scale: 1,
            url: '/zgis-map/public/icon/ic_cl.svg',
            height: 16
          },
          resultField: '',
          type: 'rest',
          geoField: 'location',
          coverEnabled: false,
          maxFeatures: 20000,
          minVisibleAltitude: 0,
          maxVisibleAltitude: 1.7976931348623157e308,
          tableName: '',
          heatRadius: 30,
          cover: {
            minLevel: 18,
            minCameraHeight: 100000,
            width: 30,
            enabled: true,
            height: 100
          },
          initDataFields: 'TITLE',
          supportCheck: true,
          model: {
            minimumPixelSize: 0,
            maxVisibleAltitude: 1.7976931348623157e308,
            scale: 1,
            url: ''
          },
          weightField: '',
          datasourceName: '11111',
          fillByField: false,
          wktField: '',
          latField: '',
          heatMap: false,
          calloutMaxVisibleAltitude: 1.7976931348623157e308,
          disableDepthTest: false,
          showCallout: false,
          indexName: '',
          dataFormat: 'point',
          datasetName: 'tratitional_villages_point_1',
          label: {
            labelOffsetY: 10,
            labelOffsetX: 0,
            fontFamily: 'Microsoft YaHei',
            field: 'TITLE',
            outlineWidth: 1,
            hideTitle: false,
            color: 'rgba(255, 255, 255, 0.95)',
            fontSize: 18,
            align: 'top',
            strokeColor: 'rgba(255, 255, 255, 0)',
            textMaxWidth: 100
          },
          fill: 'rgba(0,0,255,0.2)',
          stroke: 'rgba(0, 0, 0, 1)',
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/data-WorkSpace/rest/data',
          filter: '',
          offsetHeight: 0,
          header: '',
          geometryField: '',
          fillByFieldColorConfig: {
            mode: 'single'
          },
          lonField: ''
        },
        propertyId: '',
        key: 'ceshi'
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 'map',
        autoLocate: false,
        subdomains: '',
        defaultLoad: true,
        name: '省级传统村落行政村范围',
        showPopup: true,
        id: 'fb1d9263-2c88-4132-f8d4-358e5e8402ae',
        fields: [],
        config: {
          highlightColor: '#0afbf7',
          maximumLevel: 20,
          transparentBackColor: '#000000',
          header: '',
          transparentBackColorTolerance: 0,
          attrGeometryType: '',
          type: 'supermap',
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/map-WorkSpace1/rest/maps/tratitional_villages_province_polygon_1%40DataSource',
          minimumLevel: 0,
          allowAreaFilter: false,
          zIndex: 999
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '/zgis-map/public/legend-icon/legend_传统村落名录.svg',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 'data',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '浙江省中国传统村落名录',
        showPopup: true,
        id: '71057aec-84a7-405c-ae13-aaefa75d5e21',
        fields: [
          {
            prop: 'village',
            show: true,
            label: '名称'
          },
          {
            prop: 'province',
            show: true,
            label: '省'
          },
          {
            prop: 'city',
            show: true,
            label: '市'
          },
          {
            prop: 'county',
            show: true,
            label: '县'
          },
          {
            prop: 'town',
            show: true,
            label: '镇'
          },
          {
            prop: 'title',
            show: true,
            label: '地址'
          },
          {
            prop: 'batch',
            show: true,
            label: '批次'
          }
        ],
        config: {
          heightField: '',
          idField: '',
          cluster: 0,
          maximumLevel: 22,
          requestMethod: 'GET',
          icon: {
            width: 22,
            scale: 1,
            url: '/zgis-map/public/icon/传统村落名录.svg',
            height: 22
          },
          resultField: '',
          type: 'rest',
          geoField: 'location',
          coverEnabled: false,
          maxFeatures: 20000,
          minVisibleAltitude: 0,
          maxVisibleAltitude: 1.7976931348623157e308,
          tableName: '',
          heatRadius: 30,
          cover: {
            minLevel: 16,
            minCameraHeight: -1000,
            width: 100,
            enabled: true,
            height: 100
          },
          initDataFields: '',
          supportCheck: true,
          transparentBackColorTolerance: 0,
          attrGeometryType: '',
          model: {
            minimumPixelSize: 0,
            maxVisibleAltitude: 1.7976931348623157e308,
            scale: 1,
            url: ''
          },
          weightField: '',
          datasourceName: 'zhejiang_provincial_traditional_villages_2025072',
          fillByField: false,
          wktField: '',
          minimumLevel: 0,
          zIndex: 999,
          latField: '',
          heatMap: false,
          calloutMaxVisibleAltitude: 1.7976931348623157e308,
          disableDepthTest: false,
          showCallout: false,
          indexName: '',
          dataFormat: 'point',
          datasetName: '浙江省_传统村落',
          label: {
            labelOffsetY: 18,
            labelOffsetX: 0,
            fontFamily: 'Microsoft YaHei',
            field: 'VILLAGE',
            outlineWidth: 1,
            hideTitle: false,
            color: 'rgba(249, 249, 249, 1)',
            fontSize: 18,
            align: 'top',
            strokeColor: 'rgba(0, 0, 0, 1)',
            textMaxWidth: 100
          },
          fill: 'rgba(0,0,255,0.2)',
          stroke: 'rgba(0,0,255,1)',
          url: '/services/data-zhejiang_provincial_traditional_villages_2025072/rest/data',
          filter: '',
          highlightColor: '#0afbf7',
          transparentBackColor: '#000000',
          offsetHeight: 0,
          header: '',
          geometryField: '',
          fillByFieldColorConfig: {
            mode: 'single'
          },
          lonField: ''
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '/zgis-map/public/legend-icon/legend_传统村落分布.svg',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 'data',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '传统村落分布',
        showPopup: true,
        id: '8a663c75-697e-4a3c-9d9f-ccbf37b0b569',
        fields: [
          {
            prop: 'village',
            show: true,
            label: '名称'
          },
          {
            prop: 'province',
            show: true,
            label: '省'
          },
          {
            prop: 'city',
            show: true,
            label: '市'
          },
          {
            prop: 'county',
            show: true,
            label: '县'
          },
          {
            prop: 'town',
            show: true,
            label: '镇'
          },
          {
            prop: 'title',
            show: true,
            label: '地址'
          },
          {
            prop: 'batch',
            show: true,
            label: '批次'
          }
        ],
        config: {
          heightField: '',
          idField: '',
          cluster: 0,
          maximumLevel: 22,
          requestMethod: 'GET',
          icon: {
            width: 22,
            scale: 1,
            url: '/zgis-map/public/icon/传统村落分布.svg',
            height: 22
          },
          resultField: '',
          type: 'rest',
          geoField: 'location',
          coverEnabled: false,
          maxFeatures: 20000,
          minVisibleAltitude: 0,
          maxVisibleAltitude: 1.7976931348623157e308,
          tableName: '',
          heatRadius: 30,
          cover: {
            minLevel: 16,
            minCameraHeight: -1000,
            width: 100,
            enabled: true,
            height: 100
          },
          initDataFields: '',
          supportCheck: true,
          transparentBackColorTolerance: 0,
          attrGeometryType: '',
          model: {
            minimumPixelSize: 0,
            maxVisibleAltitude: 1.7976931348623157e308,
            scale: 1,
            url: ''
          },
          weightField: '',
          datasourceName: 'zhejiang_provincial_traditional_villages_2025072',
          fillByField: false,
          wktField: '',
          minimumLevel: 0,
          zIndex: 999,
          latField: '',
          heatMap: false,
          calloutMaxVisibleAltitude: 1.7976931348623157e308,
          disableDepthTest: false,
          showCallout: false,
          indexName: '',
          dataFormat: 'point',
          datasetName: '浙江省_传统村落',
          label: {
            labelOffsetY: 18,
            labelOffsetX: 0,
            fontFamily: 'Microsoft YaHei',
            field: 'VILLAGE',
            outlineWidth: 1,
            hideTitle: false,
            color: 'rgba(249, 249, 249, 1)',
            fontSize: 18,
            align: 'top',
            strokeColor: 'rgba(0, 0, 0, 1)',
            textMaxWidth: 100
          },
          fill: 'rgba(0,0,255,0.2)',
          stroke: 'rgba(0,0,255,1)',
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/data-zhejiang_provincial_traditional_villages_2025072/rest/data',
          filter: '',
          highlightColor: '#0afbf7',
          transparentBackColor: '#000000',
          offsetHeight: 0,
          header: '',
          geometryField: '',
          fillByFieldColorConfig: {
            mode: 'single'
          },
          lonField: ''
        },
        propertyId: '',
        key: ''
      }
    ],
    name: '传统村落保护专项地图',
    id: 'ef928367-8c2d-4cf8-abe1-e74d97e94966',
    checkEnabled: false,
    config: {}
  },
  {
    children: [
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 'terrain',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '浙江省100m地形服务',
        showPopup: true,
        id: '10180b9f-ac66-47fe-f957-00bfd90c7d2b',
        fields: [],
        config: {
          isSct: true,
          header: '',
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/dem100m/rest/realspace'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '浙规院实景三维点云',
        id: 'f980020d-cf3d-4b56-a6a7-dd6f5381c53a',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/zjplan_high_260318-new/rest/realspace/datas/zjplan_high_260318-4/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '浙规院BIM建筑模型v1版',
        id: '6612af8b-30a2-455a-8584-6b6a935bc55b',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: true,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 101,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/zjplan_reproject_260317/rest/realspace/datas/zjplan_reproject_260317/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '嵊泗县黄龙乡峙岙村历史文化名村倾斜摄影模型',
        id: 'a80236fb-001f-4c15-e250-f6a8790d9349',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_zhiao/rest/realspace/datas/Config_zhiao/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '岱山县秀山乡秀北村历史文化名村倾斜摄影模型',
        id: '7d22a720-7822-4197-8449-37a16b39afbb',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_xiubei/rest/realspace/datas/Config_xiubei/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '岱山县东沙历史文化名镇倾斜摄影模型',
        id: 'ca6cd5c9-9ea4-4ce8-8ef8-135fd9a88b23',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_dongsha/rest/realspace/datas/Config_dongsha/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '定海区岑港街道里钓山村历史文化名村倾斜摄影模型',
        id: '6da954d0-b01a-474e-a124-062ff0252683',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_lidiaoshan/rest/realspace/datas/Config_lidiaoshan/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '定海区金塘镇大鹏岛村历史文化名村倾斜摄影模型',
        id: 'cc221cc9-3cf5-44b8-c6db-f2a0596e8cac',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_dapengdao/rest/realspace/datas/Config_dapengdao/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '定海区马岙历史文化名镇倾斜摄影模型',
        id: '95eb527f-2f8a-424d-c297-11ed770f8c69',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_maao/rest/realspace/datas/Config_maao/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '定海区东大街历史文化街区倾斜摄影模型',
        id: 'd149d693-6c53-42ca-e844-2fd0c957cef5',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_dongdajie/rest/realspace/datas/Config_dongdajie/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '定海区留方路历史文化街区倾斜摄影模型',
        id: '94a7eb8d-116b-4770-8e52-77915d81cc72',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_liufanglu/rest/realspace/datas/Config_liufanglu/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '定海区中大街历史文化街区倾斜摄影模型',
        id: '4c377120-ed00-40e7-ce90-77476dd922c4',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_zhongdajie/rest/realspace/datas/Config_2/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: 's3m',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '定海区东管庙弄历史文化街区倾斜摄影模型',
        id: 'ec80e6f2-8a93-421c-ad63-1bea2b1ae866',
        fields: [],
        config: {
          waterBrightness: 1,
          isCameraController: false,
          bottomAltitudeOffset: 0,
          orderIndependentTranslucency: true,
          lineWidth: 1,
          dthServerId: '',
          dthColor: 'rgba(255,0,0,0.3)',
          saturation: 1,
          waterColor: '',
          directLightEnabled: false,
          haveFloors: false,
          floors: [],
          dthClickBuffer: 0,
          alpha: 1,
          loadMode: 'Child_Priority_NonLinear',
          directLightIntensity: 0.1,
          textureUVLayerNames: '',
          residentRootTile: false,
          waterbodySize: 0,
          isGeoTilesRootNodeSave: false,
          fillForeColor: '#ffffff',
          textureUVSpeedX: 0,
          textureUVSpeedY: 0,
          isPipeline: false,
          pbrUrls: '',
          waterParameterEnabled: false,
          wireFrameMode: 1,
          loadPBR: false,
          lineColor: '#ffffff',
          isGeoTilesSave: false,
          waveDirection: 180,
          url: 'http://zjplan.xyz:18858/api/prod/220/8090/iserver/services/3D_dongguanmiao_v2/rest/realspace/datas/Config_dongguanmiao/config',
          waveStrength: 0,
          brightness: 1,
          isAttributesSave: false,
          dthBuffer: 0,
          contrast: 1,
          useCustomAppearSetting: false,
          clearMemoryImmediately: true,
          header: '',
          fillStyle: 0,
          lodRangeScale: 1,
          waterLayerNames: '',
          partlyTransparent: false,
          dthEnabled: false
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '金华燕尾洲公园_3DTiles',
        showPopup: true,
        id: '8a6443cf-8b8a-4953-b9ed-f6d09b9f9f62',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://tdt.zrzyj.jinhua.gov.cn:9443/3d/3-%E7%87%95%E5%B0%BE%E6%B4%B2%E5%85%AC%E5%9B%AD&%E9%87%91%E5%8D%8E%E4%B9%8B%E5%85%89&%E5%A9%BA%E5%89%A7%E5%8D%9A%E7%89%A9%E9%A6%86/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '杨家堂倾斜摄影_3DTiles',
        id: '87bb262a-6b01-4da6-ad03-5080af111a21',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'http://47.99.47.79:18215/api/prod/28/80/data/%E4%BC%A0%E7%BB%9F%E6%9D%91%E8%90%BD/%E6%9D%BE%E9%98%B3/%E5%80%BE%E6%96%9C%E6%91%84%E5%BD%B1/%E6%9D%A8%E5%AE%B6%E5%A0%82/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '余杭倾斜摄影_3DTiles',
        id: 'afebdcfa-6028-4f45-c20e-5c47fec2e83c',
        fields: [],
        config: {
          isSuperMapiServer: false,
          url: 'https://hzxtkj.cn:8888/01_mapservice/3dmap/3dtiles/2023/wlkjc2/Scene/Production_3.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '来自浙江省地理公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '杭州奥体中心_3dtiles',
        id: 'd6b4af03-b55a-4eea-97ca-dd0607f41609',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://t.hangzhoumap.gov.cn/3dtile/atzx/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '杭州西溪湿地_3dtiles',
        id: '4d75d4bd-257f-4c04-fe12-4ad503fd5c30',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://t.hangzhoumap.gov.cn/3dtile/xxsd/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '湖州东吴银泰_3dtiles',
        id: '9664e119-d06b-423b-bfe6-f8609cce6486',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://zhejiang.tianditu.gov.cn/huzhou/hztdt/hz_bzxjz/bzxjz04/3dtiles/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '湖州奥体中心_3dtiles',
        id: '40b4d7a3-a839-450a-d095-7b0faef35ac0',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://zhejiang.tianditu.gov.cn/huzhou/hztdt/hz_bzxjz/bzxjz06/3dtiles/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '湖州中医院_3dtiles',
        id: 'b9dea49d-a070-47c2-b96f-ee0bf5696d39',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://zhejiang.tianditu.gov.cn/huzhou/hztdt/hz_bzxjz/bzxjz03/3dtiles/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '湖州安吉余村_3dtiles',
        id: 'e261b62e-0578-4077-96b5-6ee915f134d0',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://ditu.zjzwfw.gov.cn/3dtiles/service/anji_yucun/tileset.json?token=f07bddf8-e4ca-4501-b608-0c50dae58e67'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '嘉兴南湖_3dtiles',
        id: '998c318d-abae-4030-b07d-4ff64854e890',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://zrzyhghj1.jiaxing.gov.cn/tdtsjsw/nhjq_pianyi/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '嘉兴火车站_3dtiles',
        id: '17f2b1f8-92b8-4aab-e55b-db6b0819cd71',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://zrzyhghj1.jiaxing.gov.cn/tdtsjsw/jxhcz_pianyi/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '嘉兴月河_3dtiles',
        id: '61ef265c-425f-4542-d22f-7fcd57423457',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://zrzyhghj1.jiaxing.gov.cn/tdtsjsw/yuehe_pianyi/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '嘉兴南湖革命纪念馆_3dtiles',
        id: '451c319e-7dba-4a23-b79a-f0c0f98865d7',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://zrzyhghj1.jiaxing.gov.cn/tdtsjsw/nhgmjng_pianyi/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '嘉兴子城_3dtiles',
        id: '802ff97e-6649-45b3-9336-2a0e95e2101d',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://zrzyhghj1.jiaxing.gov.cn/tdtsjsw/zicheng_pianyi/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '金华人民广场_3dtiles',
        id: 'f62e71a5-17fb-4dcd-e669-783c58e59228',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://tdt.zrzyj.jinhua.gov.cn:9443/3d/7-%E4%BA%BA%E6%B0%91%E5%B9%BF%E5%9C%BA&%E9%87%91%E5%8D%8E%E6%B0%B8%E7%9B%9B&%E9%87%91%E5%8D%8E%E6%81%92%E5%A4%A7/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '金华赤山公园_3dtiles',
        id: '098fbac2-909c-4797-b16c-0137c2a36f57',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://tdt.zrzyj.jinhua.gov.cn:9443/3d/9-%E8%B5%A4%E5%B1%B1%E5%85%AC%E5%9B%AD/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '金华之心_3dtiles',
        id: '9072ad9d-bbf3-481f-e0ef-53a15dc0dd99',
        fields: [],
        config: {
          isSuperMapiServer: false,
          header: '',
          url: 'https://tdt.zrzyj.jinhua.gov.cn:9443/3d/6-%E9%87%91%E5%8D%8E%E4%B9%8B%E5%BF%83/tileset.json'
        },
        propertyId: '',
        key: ''
      },
      {
        resourceId: '',
        legendIcon: '',
        locateParams: '',
        legend: '',
        remark: '浙江省地理信息公共服务平台',
        source: 'DEFAULT',
        type: '3dtiles',
        autoLocate: false,
        subdomains: '',
        defaultLoad: false,
        name: '舟山观音文化园_3dtiles',
        id: '09f14c07-53d6-4103-fcb9-77ce57b71343',
        fields: [],
        config: {
          header: '',
          url: 'https://zhejiang.tianditu.gov.cn/zhoushan/3dgisservice/gywhy/tileset.json'
        },
        propertyId: '',
        key: ''
      }
    ],
    name: '三维地图',
    id: '17ef6460-8885-4b78-ca45-f0d24bb4791c',
    checkEnabled: false,
    config: {}
  }
]
</script>

<template>
  <WebScene v-bind="defaultProps" target="scene">
    <SceneLayerManager
      scene-target="scene"
      :layer-config="layerConfig"
      :collapsed="false"
      :style="{ width: '266px', height: '360px' }"
    />
  </WebScene>
</template>
