  
name: Auto Sync
on: [push,create,delete]
jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.GITEE_URL }}
          ssh_private_key:
            ${{ secrets.GITEE_KEY }}
